import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, RefreshCw } from 'lucide-react';

async function api(url:string,options:RequestInit={}){const csrf=document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content||'';const response=await fetch(url,{...options,headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf,...(options.headers||{})}});const text=await response.text();let data:any;try{data=JSON.parse(text)}catch{throw new Error('Sales data could not be read. Please sign in again.')}if(!response.ok)throw new Error(data.message||'Sales data could not be loaded.');return data}
const labels:Record<string,string>={customer_order:'Customer order',quotation:'Quotation',invoice:'Invoice',return:'Return'};
const money=(value:any,currency='RWF')=>new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:currency==='RWF'?0:2}).format(Number(value||0));

export default function SalesOverviewPage({can=()=>true}:{can?:(permission:string)=>boolean}){
 const[data,setData]=useState<any>(null),[tab,setTab]=useState('customer_order'),[loading,setLoading]=useState(true),[busy,setBusy]=useState<number|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState('');const[updated,setUpdated]=useState<Date|null>(null);
 const load=async(silent=false)=>{if(!silent)setLoading(true);try{setData(await api('/api/sales/overview'));setUpdated(new Date());setError('')}catch(reason:any){if(!silent)setError(reason.message)}finally{if(!silent)setLoading(false)}};
 useEffect(()=>{load();const timer=window.setInterval(()=>load(true),15000);return()=>window.clearInterval(timer)},[]);
 const summary=data?.summary||{},rows=useMemo(()=>(data?.documents?.data||[]).filter((item:any)=>item.document_type===tab),[data,tab]),title=labels[tab]+'s';
 const decide=async(item:any,decision:'accept'|'reject')=>{const reason=decision==='reject'?window.prompt('Reason for rejecting this order:'):'';if(decision==='reject'&&reason===null)return;if(decision==='accept'&&!window.confirm(`Accept order ${item.document_number}?`))return;setBusy(item.id);setError('');setSuccess('');try{const result=await api(`/api/sales/orders/${item.id}/decision`,{method:'PATCH',body:JSON.stringify({decision,reason})});setSuccess(result.message);await load(true)}catch(reason:any){setError(reason.message)}finally{setBusy(null)}};
 return <section className="module-page sales-live-page">
  <div className="module-hero"><div className="module-title"><div><div className="eyebrow"><i/>LIVE SALES DATA</div><h1>Incoming customer orders</h1><p>Review customer demand before the logistics team prepares and dispatches each order.</p><small className="sales-updated">{updated?'Last updated '+updated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Connecting to sales records...'}</small></div></div><button className="secondary-btn" disabled={loading} onClick={()=>load()}><RefreshCw className={loading?'spin':''} size={16}/>{loading?'Refreshing...':'Refresh data'}</button></div>
  {error&&<div className="admin-alert error"><AlertTriangle size={18}/>{error}</div>}{success&&<div className="admin-alert success">{success}</div>}
  <div className="sales-metrics"><Metric label="Customer orders" value={summary.customer_orders}/><Metric label="Awaiting review" value={(data?.documents?.data||[]).filter((x:any)=>x.document_type==='customer_order'&&['draft','pending','submitted'].includes(x.status)).length}/><Metric label="Active orders" value={summary.active_orders}/><Metric label="Completed orders" value={summary.completed_orders}/></div>
  <div className="module-tabs sales-tabs">{[['customer_order','Customer orders',summary.customer_orders],['quotation','Quotations',summary.quotations],['invoice','Invoices',summary.invoices],['return','Returns',summary.returns]].map(([key,label,count]:any)=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{Number(count||0).toLocaleString()}</span></button>)}</div>
  <section className="panel sales-records"><header><div><h2>{title}</h2><p>Accept valid incoming orders or reject them with a recorded reason.</p></div></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Number</th><th>Customer</th><th>Date</th><th>Items</th><th>Total</th>{tab==='invoice'&&<th>Paid</th>}<th>Status</th><th>Due date</th>{tab==='customer_order'&&can('sales.fulfill')&&<th>Actions</th>}</tr></thead><tbody>{rows.length?rows.map((item:any)=><tr key={item.id}><td><b>{item.document_number}</b></td><td><b>{item.customer_name}</b>{item.customer_email&&<small>{item.customer_email}</small>}</td><td>{new Date(item.document_date+'T12:00:00').toLocaleDateString()}</td><td>{Number(item.item_count||0).toLocaleString()}</td><td>{money(item.total_amount,item.currency_code)}</td>{tab==='invoice'&&<td>{money(item.paid_amount,item.currency_code)}</td>}<td><span className={'admin-status '+item.status}>{String(item.status).replaceAll('_',' ')}</span></td><td>{item.due_date?new Date(item.due_date+'T12:00:00').toLocaleDateString():'Not set'}</td>{tab==='customer_order'&&can('sales.fulfill')&&<td><div className="workflow-actions">{['draft','pending','submitted'].includes(item.status)?<><button className="primary-btn" disabled={busy===item.id} onClick={()=>decide(item,'accept')}>Accept</button><button className="secondary-btn" disabled={busy===item.id} onClick={()=>decide(item,'reject')}>Reject</button></>:<small>Reviewed</small>}</div></td>}</tr>):<tr><td colSpan={9}><div className="sales-empty"><b>No {title.toLowerCase()} recorded</b><span>New sales records will appear here automatically.</span></div></td></tr>}</tbody></table></div></section>
 </section>
}
function Metric({label,value}:any){return <article className="panel"><small>{label}</small><strong>{Number(value||0).toLocaleString()}</strong></article>}
