import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Plus, RefreshCw } from 'lucide-react';

async function api(url='/api/logistics/overview',options:RequestInit={}){const csrf=document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content||'';const response=await fetch(url,{...options,headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf,...(options.headers||{})}});const text=await response.text();let data:any;try{data=JSON.parse(text)}catch{throw new Error('Delivery data could not be read. Please sign in again.')}if(!response.ok)throw new Error(data.message||'Delivery data could not be loaded.');return data}
const statusLabel:Record<string,string>={planned:'Planned',ready:'Ready for dispatch',in_transit:'In transit',delivered:'Delivered',delayed:'Delayed',cancelled:'Cancelled',available:'Available',assigned:'Assigned',maintenance:'Under maintenance',inactive:'Inactive'};
const blank={sales_document_id:'',delivery_vehicle_id:'',destination:'',package_count:'1',total_weight:'',weight_unit:'kg',planned_dispatch_at:'',delivery_notes:''};

export default function LogisticsOverviewPage({initialTab='shipments',can=()=>true}:{initialTab?:string;can?:(permission:string)=>boolean}){
 const[data,setData]=useState<any>(null),[tab,setTab]=useState(initialTab),[loading,setLoading]=useState(true),[busy,setBusy]=useState<number|string|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[showCreate,setShowCreate]=useState(false),[form,setForm]=useState<any>(blank);const[updated,setUpdated]=useState<Date|null>(null);
 const load=async(silent=false)=>{if(!silent)setLoading(true);try{setData(await api());setUpdated(new Date());setError('')}catch(reason:any){if(!silent)setError(reason.message)}finally{if(!silent)setLoading(false)}};
 useEffect(()=>{load();const timer=window.setInterval(()=>load(true),15000);return()=>window.clearInterval(timer)},[]);useEffect(()=>setTab(initialTab),[initialTab]);
 const summary=data?.summary||{},shipments=data?.shipments?.data||[],rows=useMemo(()=>tab==='dispatch'?shipments.filter((x:any)=>['planned','ready','in_transit'].includes(x.status)):tab==='proof'?shipments.filter((x:any)=>x.status==='delivered'):shipments,[shipments,tab]);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy('create');setError('');try{const result=await api('/api/logistics/shipments',{method:'POST',body:JSON.stringify({...form,delivery_vehicle_id:form.delivery_vehicle_id||null,total_weight:form.total_weight||0,planned_dispatch_at:form.planned_dispatch_at||null})});setSuccess(result.message);setForm(blank);setShowCreate(false);await load(true)}catch(reason:any){setError(reason.message)}finally{setBusy(null)}};
 const action=async(item:any,name:string)=>{let payload:any={action:name};if(name==='ready'){const vehicle=window.prompt('Enter the vehicle ID to assign:',item.delivery_vehicle_id||'');if(!vehicle)return;payload.delivery_vehicle_id=vehicle}if(name==='deliver'){const receiver=window.prompt('Who received the delivery?');if(!receiver)return;const proof=window.prompt('Proof/reference number:');if(!proof)return;payload={action:name,received_by:receiver,proof_reference:proof}}if(name==='cancel'&&!window.confirm(`Cancel shipment ${item.shipment_number}?`))return;setBusy(item.id);setError('');try{const result=await api(`/api/logistics/shipments/${item.id}`,{method:'PATCH',body:JSON.stringify(payload)});setSuccess(result.message);await load(true)}catch(reason:any){setError(reason.message)}finally{setBusy(null)}};
 return <section className="module-page logistics-live-page">
  <div className="module-hero"><div className="module-title"><div><div className="eyebrow"><i/>LIVE DELIVERY DATA</div><h1>Logistics control centre</h1><p>Prepare accepted orders, assign vehicles, dispatch shipments and record proof of delivery.</p><small className="sales-updated">{updated?'Last updated '+updated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Connecting to delivery records...'}</small></div></div><div className="workflow-actions">{can('logistics.plan')&&<button className="primary-btn" onClick={()=>setShowCreate(!showCreate)}><Plus size={16}/>New shipment</button>}<button className="secondary-btn" disabled={loading} onClick={()=>load()}><RefreshCw className={loading?'spin':''} size={16}/>Refresh</button></div></div>
  {error&&<div className="admin-alert error"><AlertTriangle size={18}/>{error}</div>}{success&&<div className="admin-alert success">{success}</div>}
  <div className="sales-metrics"><Metric label="All shipments" value={summary.total_shipments}/><Metric label="Ready" value={summary.ready}/><Metric label="In transit" value={summary.in_transit}/><Metric label="Delivered orders" value={summary.delivered}/><Metric label="Delivered items" value={summary.delivered_items}/><Metric label="Delivered packages" value={summary.delivered_packages}/><Metric label="Delivered today" value={summary.delivered_today}/><Metric label="Delayed" value={summary.delayed}/></div>
  {showCreate&&<form className="panel admin-form quality-form" onSubmit={submit}><h2>Create shipment from an accepted order</h2><div className="form-grid"><label>Accepted order<select required value={form.sales_document_id} onChange={e=>setForm({...form,sales_document_id:e.target.value})}><option value="">Choose order</option>{(data?.incoming_orders||[]).map((x:any)=><option key={x.id} value={x.id}>{x.document_number} — {x.customer_name} ({x.item_count} items)</option>)}</select></label><label>Vehicle<select value={form.delivery_vehicle_id} onChange={e=>setForm({...form,delivery_vehicle_id:e.target.value})}><option value="">Assign later</option>{(data?.vehicles||[]).filter((x:any)=>x.status==='available').map((x:any)=><option key={x.id} value={x.id}>{x.id} — {x.registration_number} / {x.driver_name||'No driver'}</option>)}</select></label><label>Destination<input required value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/></label><label>Packages<input required min="1" type="number" value={form.package_count} onChange={e=>setForm({...form,package_count:e.target.value})}/></label><label>Total weight<input min="0" step="0.001" type="number" value={form.total_weight} onChange={e=>setForm({...form,total_weight:e.target.value})}/></label><label>Weight unit<input value={form.weight_unit} onChange={e=>setForm({...form,weight_unit:e.target.value})}/></label><label>Planned dispatch<input type="datetime-local" value={form.planned_dispatch_at} onChange={e=>setForm({...form,planned_dispatch_at:e.target.value})}/></label><label>Delivery notes<textarea value={form.delivery_notes} onChange={e=>setForm({...form,delivery_notes:e.target.value})}/></label></div><div className="workflow-actions"><button className="secondary-btn" type="button" onClick={()=>setShowCreate(false)}>Cancel</button><button className="primary-btn" disabled={busy==='create'}>{busy==='create'?'Creating...':'Create shipment'}</button></div></form>}
  <div className="module-tabs sales-tabs">{[['shipments','Shipments',summary.total_shipments],['dispatch','Dispatch board',Number(summary.ready||0)+Number(summary.in_transit||0)+Number(summary.planned||0)],['vehicles','Vehicles and drivers',summary.vehicles],['proof','Delivery confirmation',summary.proof_of_delivery]].map(([key,label,count]:any)=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{Number(count||0).toLocaleString()}</span></button>)}</div>
  {tab==='vehicles'?<VehicleTable vehicles={data?.vehicles||[]}/>:<ShipmentTable rows={rows} tab={tab} busy={busy} action={action} can={can}/>}
 </section>
}
function ShipmentTable({rows,tab,busy,action,can}:any){const title=tab==='dispatch'?'Current dispatch work':tab==='proof'?'Delivery confirmations':'Shipments';return <section className="panel sales-records"><header><div><h2>{title}</h2><p>Follow every shipment from accepted order through confirmed delivery.</p></div></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Shipment</th><th>Customer</th><th>Destination</th><th>Packages</th><th>Vehicle / driver</th><th>Status</th><th>Dispatch time</th><th>Actions</th></tr></thead><tbody>{rows.length?rows.map((item:any)=><tr key={item.id}><td><b>{item.shipment_number}</b>{item.sales_document?.document_number&&<small>Order {item.sales_document.document_number}</small>}</td><td>{item.customer_name}</td><td>{item.destination}</td><td>{Number(item.package_count||0).toLocaleString()}<small>{Number(item.total_weight||0).toLocaleString()} {item.weight_unit}</small></td><td>{item.vehicle?.registration_number||'Not assigned'}<small>{item.vehicle?.driver_name||'No driver'}</small></td><td><span className={'admin-status '+item.status}>{statusLabel[item.status]||item.status}</span></td><td>{item.dispatched_at?new Date(item.dispatched_at).toLocaleString():item.planned_dispatch_at?new Date(item.planned_dispatch_at).toLocaleString():'Not set'}</td><td><div className="workflow-actions">{item.status==='planned'&&can('logistics.plan')&&<button className="secondary-btn" disabled={busy===item.id} onClick={()=>action(item,'ready')}>Assign vehicle</button>}{item.status==='ready'&&can('logistics.dispatch')&&<button className="primary-btn" disabled={busy===item.id} onClick={()=>action(item,'dispatch')}>Dispatch</button>}{item.status==='in_transit'&&can('logistics.deliver')&&<button className="primary-btn" disabled={busy===item.id} onClick={()=>action(item,'deliver')}>Confirm delivery</button>}{['planned','ready'].includes(item.status)&&can('logistics.plan')&&<button className="secondary-btn" disabled={busy===item.id} onClick={()=>action(item,'cancel')}>Cancel</button>}{item.status==='delivered'&&<small>{item.received_by}<br/>{item.proof_reference}</small>}</div></td></tr>):<tr><td colSpan={8}><Empty text={tab==='proof'?'No delivery confirmations recorded yet.':'No shipment records have been added yet.'}/></td></tr>}</tbody></table></div></section>}
function VehicleTable({vehicles}:any){return <section className="panel sales-records"><header><div><h2>Vehicles and drivers</h2><p>Current delivery resources registered for this factory.</p></div></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Registration</th><th>Vehicle type</th><th>Driver</th><th>Phone</th><th>Capacity</th><th>Status</th></tr></thead><tbody>{vehicles.length?vehicles.map((x:any)=><tr key={x.id}><td>{x.id}</td><td><b>{x.registration_number}</b></td><td>{x.vehicle_type}</td><td>{x.driver_name||'Not assigned'}</td><td>{x.driver_phone||'Not set'}</td><td>{x.capacity?Number(x.capacity).toLocaleString()+' '+(x.capacity_unit||''):'Not set'}</td><td><span className={'admin-status '+x.status}>{statusLabel[x.status]||x.status}</span></td></tr>):<tr><td colSpan={7}><Empty text="No delivery vehicles have been registered yet."/></td></tr>}</tbody></table></div></section>}
function Metric({label,value}:any){return <article className="panel"><small>{label}</small><strong>{Number(value||0).toLocaleString()}</strong></article>}
function Empty({text}:any){return <div className="sales-empty"><b>No records available</b><span>{text}</span></div>}
