import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, RefreshCw } from 'lucide-react';

async function api(){const response=await fetch('/api/logistics/overview',{headers:{Accept:'application/json'}});const text=await response.text();let data:any;try{data=JSON.parse(text)}catch{throw new Error('Delivery data could not be read. Please sign in again.')}if(!response.ok)throw new Error(data.message||'Delivery data could not be loaded.');return data}
const statusLabel:Record<string,string>={planned:'Planned',ready:'Ready for dispatch',in_transit:'In transit',delivered:'Delivered',delayed:'Delayed',cancelled:'Cancelled',available:'Available',assigned:'Assigned',maintenance:'Under maintenance',inactive:'Inactive'};

export default function LogisticsOverviewPage({initialTab='shipments'}:{initialTab?:string}){
    const [data,setData]=useState<any>(null);const [tab,setTab]=useState(initialTab);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [updated,setUpdated]=useState<Date|null>(null);
    const load=async(silent=false)=>{if(!silent)setLoading(true);try{setData(await api());setUpdated(new Date());setError('')}catch(reason:any){if(!silent)setError(reason.message)}finally{if(!silent)setLoading(false)}};
    useEffect(()=>{load();const timer=window.setInterval(()=>load(true),15000);return()=>window.clearInterval(timer)},[]);
    useEffect(()=>setTab(initialTab),[initialTab]);
    const summary=data?.summary||{};const shipments=data?.shipments?.data||[];const rows=useMemo(()=>tab==='dispatch'?shipments.filter((item:any)=>['planned','ready','in_transit'].includes(item.status)):tab==='proof'?shipments.filter((item:any)=>item.delivered_at||item.proof_reference):shipments,[shipments,tab]);
    return <section className="module-page logistics-live-page">
        <div className="module-hero"><div className="module-title"><div><div className="eyebrow"><i></i>LIVE DELIVERY DATA</div><h1>Delivery overview</h1><p>Monitor shipments, dispatch progress, vehicles, drivers and delivery confirmation recorded by your logistics team.</p><small className="sales-updated">{updated?'Last updated '+updated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Connecting to delivery records…'}</small></div></div><button className="secondary-btn" disabled={loading} onClick={()=>load()}><RefreshCw className={loading?'spin':''} size={16}/>{loading?'Refreshing…':'Refresh data'}</button></div>
        {error&&<div className="admin-alert error"><AlertTriangle size={18}/>{error}</div>}
        <div className="sales-metrics"><Metric label="All shipments" value={summary.total_shipments}/><Metric label="Ready to dispatch" value={summary.ready}/><Metric label="In transit" value={summary.in_transit}/><Metric label="Delivered" value={summary.delivered}/></div>
        <div className="module-tabs sales-tabs">{[['shipments','Shipments',summary.total_shipments],['dispatch','Dispatch board',Number(summary.ready||0)+Number(summary.in_transit||0)+Number(summary.planned||0)],['vehicles','Vehicles and drivers',summary.vehicles],['proof','Delivery confirmation',summary.proof_of_delivery]].map(([key,label,count]:any)=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{Number(count||0).toLocaleString()}</span></button>)}</div>
        {tab==='vehicles'?<VehicleTable vehicles={data?.vehicles||[]}/>:<ShipmentTable rows={rows} tab={tab}/>} 
    </section>;
}
function ShipmentTable({rows,tab}:any){const title=tab==='dispatch'?'Current dispatch work':tab==='proof'?'Delivery confirmations':'Shipments';return <section className="panel sales-records"><header><div><h2>{title}</h2><p>Records shown below come directly from this factory’s delivery database.</p></div></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Shipment</th><th>Customer</th><th>Destination</th><th>Packages</th><th>Vehicle / driver</th><th>Status</th><th>Dispatch time</th>{tab==='proof'&&<th>Received by</th>}</tr></thead><tbody>{rows.length?rows.map((item:any)=><tr key={item.id}><td><b>{item.shipment_number}</b>{item.sales_document?.document_number&&<small>Order {item.sales_document.document_number}</small>}</td><td>{item.customer_name}</td><td>{item.destination}</td><td>{Number(item.package_count||0).toLocaleString()}<small>{Number(item.total_weight||0).toLocaleString()} {item.weight_unit}</small></td><td>{item.vehicle?.registration_number||'Not assigned'}<small>{item.vehicle?.driver_name||'No driver'}</small></td><td><span className={'admin-status '+item.status}>{statusLabel[item.status]||item.status}</span></td><td>{item.dispatched_at?new Date(item.dispatched_at).toLocaleString():item.planned_dispatch_at?new Date(item.planned_dispatch_at).toLocaleString():'Not set'}</td>{tab==='proof'&&<td>{item.received_by||'Not confirmed'}<small>{item.delivered_at?new Date(item.delivered_at).toLocaleString():''}</small></td>}</tr>):<tr><td colSpan={tab==='proof'?8:7}><Empty text={tab==='proof'?'No delivery confirmations recorded yet.':'No shipment records have been added yet.'}/></td></tr>}</tbody></table></div></section>}
function VehicleTable({vehicles}:any){return <section className="panel sales-records"><header><div><h2>Vehicles and drivers</h2><p>Current delivery resources registered for this factory.</p></div></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Registration</th><th>Vehicle type</th><th>Driver</th><th>Phone</th><th>Capacity</th><th>Status</th></tr></thead><tbody>{vehicles.length?vehicles.map((item:any)=><tr key={item.id}><td><b>{item.registration_number}</b></td><td>{item.vehicle_type}</td><td>{item.driver_name||'Not assigned'}</td><td>{item.driver_phone||'Not set'}</td><td>{item.capacity?Number(item.capacity).toLocaleString()+' '+(item.capacity_unit||''):'Not set'}</td><td><span className={'admin-status '+item.status}>{statusLabel[item.status]||item.status}</span></td></tr>):<tr><td colSpan={6}><Empty text="No delivery vehicles have been registered yet."/></td></tr>}</tbody></table></div></section>}
function Metric({label,value}:any){return <article className="panel"><small>{label}</small><strong>{Number(value||0).toLocaleString()}</strong></article>}
function Empty({text}:any){return <div className="sales-empty"><b>No records available</b><span>{text}</span></div>}
