import React, { useEffect, useState } from 'react';
import { Activity, Factory, FileText, Plus, Printer, RefreshCw, Save, Settings, Users } from 'lucide-react';

const csrf=()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';
async function api(url:string,options:RequestInit={}){const response=await fetch(url,{...options,headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf(),...(options.headers||{})}});const text=await response.text();let payload:any;try{payload=text?JSON.parse(text):{}}catch{throw new Error('The server returned an invalid response.')}if(!response.ok)throw new Error(payload.message||Object.values(payload.errors||{}).flat().join(' ')||'Request failed.');return payload}
function Alert({error,success}:{error:string;success:string}){return <>{error&&<div className="admin-alert error">{error}</div>}{success&&<div className="admin-alert success">{success}</div>}</>}
function Heading({icon:Icon,title,description,action}:any){return <div className="module-hero"><div className="module-title"><span><Icon size={22}/></span><div><div className="eyebrow"><i></i>LIVE FACTORY MODULE</div><h1>{title}</h1><p>{description}</p></div></div>{action}</div>}

export function FlowSetupPage(){
    const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
    const load=()=>api('/api/factory/flow-suggestion').then(setData).catch(reason=>setError(reason.message));
    useEffect(load,[]);
    const apply=async()=>{setBusy(true);setError('');try{await api('/api/factory/flow-suggestion/apply',{method:'POST'});setSuccess('Recommended departments, workstations and workflow stages are ready.');await load()}catch(reason:any){setError(reason.message)}finally{setBusy(false)}};
    const suggestion=data?.suggestion;return <section className="module-page"><Heading icon={Settings} title="Factory flow setup" description="Use an industry-based structure, then assign employees to its departments and stations." action={<button className="primary-btn" disabled={busy||!suggestion} onClick={apply}><Save size={17}/>{busy?'Applying…':'Apply recommended flow'}</button>}/><Alert error={error} success={success}/><article className="panel flow-suggestion"><div className="flow-head"><div><small>REGISTERED INDUSTRY</small><h2>{String(data?.industry||'').replaceAll('_',' ')}</h2><p>{suggestion?.name}</p></div><Factory size={32}/></div><div className="flow-line">{suggestion?.departments?.map((item:any,index:number)=><div key={item.code}><span>{index+1}</span><b>{item.name}</b><small>{item.workstation_type}</small></div>)}</div></article></section>
}

export function ProductionFlowPage(){
    const [data,setData]=useState<any>(null);const [error,setError]=useState('');const load=()=>api('/api/manufacturing/overview').then(setData).catch(reason=>setError(reason.message));useEffect(()=>{load();const timer=window.setInterval(load,5000);return()=>window.clearInterval(timer)},[]);
    return <section className="module-page"><Heading icon={Factory} title="Production workflows" description="Live factory workflows and their ordered execution stages." action={<button className="secondary-btn" onClick={load}><RefreshCw size={16}/>Refresh</button>}/><Alert error={error} success=""/><div className="workflow-list">{(data?.workflows||[]).length?data.workflows.map((workflow:any)=><article className="panel" key={workflow.id}><header><div><small>{workflow.code}</small><h2>{workflow.name}</h2></div><span className="admin-status active">{workflow.status}</span></header><div className="flow-line">{workflow.stages.map((stage:any)=><div key={stage.id}><span>{stage.sequence}</span><b>{stage.name}</b><small>{stage.quality_required?'Quality approval required':(stage.expected_minutes?stage.expected_minutes+' minutes':'Operational stage')}</small></div>)}</div></article>):<div className="panel empty-state"><span><Factory size={28}/></span><h3>No workflow configured</h3><p>Open Factory Settings and apply the recommended flow for this industry.</p></div>}</div></section>
}

export function TeamManagementPage(){
    const [data,setData]=useState<any>(null);const [department,setDepartment]=useState({name:'',code:''});const [editing,setEditing]=useState<Record<number,any>>({});const [error,setError]=useState('');const [success,setSuccess]=useState('');
    const load=()=>api('/api/team/workspaces').then(setData).catch(reason=>setError(reason.message));useEffect(load,[]);
    const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/api/team/departments',{method:'POST',body:JSON.stringify(department)});setDepartment({name:'',code:''});setSuccess('Department created.');await load()}catch(reason:any){setError(reason.message)}};
    const save=async(user:any)=>{const values=editing[user.id]||{};try{await api('/api/team/users/'+user.id,{method:'PATCH',body:JSON.stringify(values)});setSuccess('Employee assignment updated.');await load()}catch(reason:any){setError(reason.message)}};
    const users=data?.users?.data||[];return <section className="module-page"><Heading icon={Users} title="Departments and employee assignments" description="Create departments and place each employee in the correct department, workstation and role."/><Alert error={error} success={success}/><form className="panel admin-form department-form" onSubmit={create}><h2>Create department</h2><div className="form-grid"><label>Department name<input required value={department.name} onChange={e=>setDepartment({...department,name:e.target.value})}/></label><label>Short code<input required maxLength={30} value={department.code} onChange={e=>setDepartment({...department,code:e.target.value.toUpperCase()})}/></label></div><button className="primary-btn"><Plus size={16}/>Create department</button></form><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Employee</th><th>Role</th><th>Department</th><th>Workstation</th><th>Job title</th><th>Action</th></tr></thead><tbody>{users.map((user:any)=>{const current=editing[user.id]||{};return <tr key={user.id}><td><b>{user.name}</b><br/><small>{user.email}</small></td><td><select value={current.role_id||user.roles?.[0]?.id||''} onChange={e=>setEditing({...editing,[user.id]:{...current,role_id:e.target.value}})}>{(data?.roles||[]).map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></td><td><select value={current.department_id??user.employee_profile?.department_id??''} onChange={e=>setEditing({...editing,[user.id]:{...current,department_id:e.target.value||null}})}><option value="">Not assigned</option>{(data?.departments||[]).map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></td><td><select value={current.workstation_id??user.employee_profile?.workstation_id??''} onChange={e=>setEditing({...editing,[user.id]:{...current,workstation_id:e.target.value||null}})}><option value="">Not assigned</option>{(data?.workstations||[]).map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></td><td><input value={current.job_title??user.employee_profile?.job_title??''} onChange={e=>setEditing({...editing,[user.id]:{...current,job_title:e.target.value}})}/></td><td><button className="table-action" onClick={()=>save(user)}>Save assignment</button></td></tr>})}</tbody></table></div></section>
}

export function ReportsPage({canExport}:{canExport:boolean}){
    const today=new Date().toISOString().slice(0,10);const [filters,setFilters]=useState({period:'week',type:'all',from:today,to:today});const [data,setData]=useState<any>(null);const [error,setError]=useState('');
    const load=()=>{const query=new URLSearchParams(filters);api('/api/reports?'+query.toString()).then(setData).catch(reason=>setError(reason.message))};useEffect(load,[]);
    return <section className="module-page report-page"><div className="no-print"><Heading icon={FileText} title="Professional factory reports" description="Filter complete factory records and print or save the report as a PDF document." action={canExport?<button className="primary-btn" disabled={!data} onClick={()=>window.print()}><Printer size={17}/>Print / Save PDF</button>:null}/><Alert error={error} success=""/><div className="panel report-filters"><label>Period<select value={filters.period} onChange={e=>setFilters({...filters,period:e.target.value})}><option value="day">Today</option><option value="week">Last 7 days</option><option value="month">This month</option><option value="custom">Custom dates</option></select></label><label>Report type<select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="all">Complete factory report</option><option value="production">Production</option><option value="inventory">Inventory movements</option><option value="team">Employees and departments</option><option value="activity">Audit activity</option></select></label>{filters.period==='custom'&&<><label>From<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label></>}<button className="primary-btn" onClick={load}><Activity size={16}/>Generate report</button></div></div>{data&&<ReportDocument data={data}/>}</section>
}
function ReportDocument({data}:any){const summary=data.summary;return <article className="report-document"><header><div><h1>{data.factory.name}</h1><p>{String(data.factory.industry_type).replaceAll('_',' ')}</p></div><div><b>FACTORY REPORT</b><span>{data.report.from} to {data.report.to}</span></div></header><section className="report-meta"><span>Generated: {new Date(data.report.generated_at).toLocaleString()}</span><span>Prepared by: {data.report.generated_by}</span><span>Type: {data.report.type}</span></section><div className="report-summary">{Object.entries(summary).map(([key,value]:any)=><div key={key}><span>{key.replaceAll('_',' ')}</span><b>{Number(value).toLocaleString()}</b></div>)}</div>{data.production.length>0&&<ReportTable title="Production details" headers={['Order','Product','Status','Planned','Completed','Rejected','Due']} rows={data.production.map((item:any)=>[item.order_number,item.item?.name,item.status,item.planned_quantity,item.completed_quantity,item.rejected_quantity,item.planned_end||'—'])}/>} {data.inventory.length>0&&<ReportTable title="Inventory movement details" headers={['Date','Item','SKU','Warehouse','Type','Quantity','Cost','Balance','Reason']} rows={data.inventory.map((item:any)=>[new Date(item.occurred_at).toLocaleString(),item.item_name,item.sku,item.warehouse_name,item.type,item.quantity_delta,item.unit_cost,item.balance_after,item.reason||'—'])}/>} {data.team.length>0&&<ReportTable title="Employees and departments" headers={['Employee no.','Name','Email','Department','Workstation','Job title','Status']} rows={data.team.map((item:any)=>[item.employee_number,item.name,item.email,item.department||'Unassigned',item.workstation||'Unassigned',item.job_title||'—',item.employment_status])}/>} {data.activities.length>0&&<ReportTable title="Audit activity" headers={['Date','User','Event','Description']} rows={data.activities.map((item:any)=>[new Date(item.created_at).toLocaleString(),item.user?.name||'System',item.event,item.description])}/>}<footer>{data.factory.name} · Generated by ICYEREKEZO OMS · {new Date(data.report.generated_at).toLocaleDateString()}</footer></article>}
function ReportTable({title,headers,rows}:any){return <section className="report-section"><h2>{title}</h2><table><thead><tr>{headers.map((item:string)=><th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row:any[],index:number)=><tr key={index}>{row.map((cell:any,cellIndex:number)=><td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></section>}
