import React,{useEffect,useState}from'react';
import{Building2,Clock3,Factory,MapPin,Save,Settings,ShieldCheck}from'lucide-react';
const csrf=()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';
async function api(url:string,options:RequestInit={}){const r=await fetch(url,{...options,headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf(),...(options.headers||{})}});const text=await r.text();let data:any;try{data=text?JSON.parse(text):{}}catch{throw new Error('The server returned an invalid response.')}if(!r.ok)throw new Error(data.message||Object.values(data.errors||{}).flat().join(' ')||'Request failed.');return data}
const Field=({label,note,children}:any)=><label>{label}{children}{note&&<small>{note}</small>}</label>;
const Card=({icon:Icon,title,note,children}:any)=><section className="panel factory-setting-card"><header><span><Icon/></span><div><h2>{title}</h2><p>{note}</p></div></header>{children}</section>;
const Check=({label,note,checked,change}:any)=><label className="switch-line"><span><b>{label}</b><small>{note}</small></span><input type="checkbox" checked={!!checked} onChange={e=>change(e.target.checked)}/></label>;
export default function FactorySettingsPage(){
 const[data,setData]=useState<any>(null),[form,setForm]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const load=async()=>{try{const x=await api('/api/factory/settings');setData(x);setForm({...x.factory,settings:{...x.settings}});setError('')}catch(e:any){setError(e.message)}};useEffect(()=>{load()},[]);
 const update=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v})),setting=(k:string,v:any)=>setForm((x:any)=>({...x,settings:{...x.settings,[k]:v}}));
 const toggleDay=(day:string)=>{const list=form.settings.working_days||[];setting('working_days',list.includes(day)?list.filter((x:string)=>x!==day):[...list,day])};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');setSuccess('');try{const x=await api('/api/factory/settings',{method:'PUT',body:JSON.stringify(form)});setData(x);setForm({...x.factory,settings:{...x.settings}});setSuccess(x.message)}catch(x:any){setError(x.message)}finally{setBusy(false)}};
 if(!form)return <section className="module-page"><div className="module-hero"><div className="module-title"><span><Settings/></span><div><h1>Factory settings</h1><p>Manage your factory profile and operating rules.</p></div></div></div>{error&&<div className="admin-alert error">{error}</div>}<div className="panel admin-loading">Loading factory settings…</div></section>;
 const days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
 return <section className="module-page factory-settings-page"><div className="module-hero"><div className="module-title"><span><Settings/></span><div><div className="eyebrow"><i/>LIVE FACTORY CONTROL</div><h1>Factory settings</h1><p>Manage identity, location, working schedule and operating rules across your factory.</p></div></div><button form="factory-settings-form" className="primary-btn" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save settings'}</button></div>{error&&<div className="admin-alert error">{error}</div>}{success&&<div className="admin-alert success">{success}</div>}<form id="factory-settings-form" onSubmit={save} className="factory-settings-grid"><div className="factory-settings-main">
 <Card icon={Building2} title="Factory profile" note="Official information shown on reports and operational documents."><div className="form-grid"><Field label="Factory name"><input required value={form.name||''} onChange={e=>update('name',e.target.value)}/></Field><Field label="Industry type" note="Only the platform administrator can change this."><input disabled value={String(form.industry_type||'').replaceAll('_',' ')}/></Field><Field label="Factory email"><input type="email" placeholder="factory@company.com" value={form.email||''} onChange={e=>update('email',e.target.value)}/></Field><Field label="Factory phone"><input placeholder="+250 7…" value={form.phone||''} onChange={e=>update('phone',e.target.value)}/></Field><Field label="Registration number"><input placeholder="Official registration number" value={form.settings.registration_number||''} onChange={e=>setting('registration_number',e.target.value)}/></Field><Field label="Tax number / TIN"><input placeholder="Tax identification number" value={form.settings.tax_number||''} onChange={e=>setting('tax_number',e.target.value)}/></Field></div></Card>
 <Card icon={MapPin} title="Location and regional settings" note="Controls report dates, language and money values."><div className="form-grid"><Field label="Street address"><input placeholder="Industrial zone, street or building" value={form.settings.address||''} onChange={e=>setting('address',e.target.value)}/></Field><Field label="City"><input placeholder="Kigali" value={form.settings.city||''} onChange={e=>setting('city',e.target.value)}/></Field><Field label="Country code"><input required maxLength={2} value={form.country_code||'RW'} onChange={e=>update('country_code',e.target.value.toUpperCase())}/></Field><Field label="Currency"><select value={form.currency_code} onChange={e=>update('currency_code',e.target.value)}>{['RWF','USD','EUR','KES','UGX'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Time zone"><select value={form.timezone} onChange={e=>update('timezone',e.target.value)}><option value="Africa/Kigali">Kigali</option><option value="Africa/Johannesburg">Johannesburg</option><option value="Africa/Nairobi">Nairobi</option><option value="Africa/Kampala">Kampala</option><option value="UTC">UTC</option></select></Field><Field label="Default language"><select value={form.default_locale} onChange={e=>update('default_locale',e.target.value)}><option value="en">English</option><option value="fr">Français</option></select></Field></div></Card>
 <Card icon={Clock3} title="Working schedule" note="Define normal operating hours and working days."><div className="form-grid"><Field label="Opening time"><input required type="time" value={form.settings.opening_time} onChange={e=>setting('opening_time',e.target.value)}/></Field><Field label="Closing time"><input required type="time" value={form.settings.closing_time} onChange={e=>setting('closing_time',e.target.value)}/></Field></div><div className="working-days">{days.map(day=><button type="button" key={day} className={form.settings.working_days.includes(day)?'active':''} onClick={()=>toggleDay(day)}>{day.slice(0,3)}</button>)}</div></Card>
 <Card icon={ShieldCheck} title="Operating controls" note="Safety rules for production and stock recording."><div className="form-grid"><Field label="Production order prefix" note={`Example: ${form.settings.production_order_prefix||'PO'}-0001`}><input required maxLength={12} value={form.settings.production_order_prefix} onChange={e=>setting('production_order_prefix',e.target.value.toUpperCase())}/></Field><Field label="Low-stock alert level"><input required type="number" min="0" value={form.settings.low_stock_alert_level} onChange={e=>setting('low_stock_alert_level',Number(e.target.value))}/></Field></div><Check label="Require production approval" note="Orders must be approved before work begins." checked={form.settings.require_production_approval} change={(v:boolean)=>setting('require_production_approval',v)}/><Check label="Require quality release" note="Finished goods need a passed quality check before release." checked={form.settings.require_quality_release} change={(v:boolean)=>setting('require_quality_release',v)}/><Check label="Allow stock below zero" note="Keep disabled to prevent issuing unavailable material." checked={form.settings.allow_negative_stock} change={(v:boolean)=>setting('allow_negative_stock',v)}/></Card>
 </div><aside className="panel factory-settings-summary"><Factory size={30}/><small>ACTIVE FACTORY</small><h2>{form.name}</h2><p>{String(form.industry_type||'').replaceAll('_',' ')}</p><dl><div><dt>Location</dt><dd>{form.settings.city||'Not set'}, {form.country_code}</dd></div><div><dt>Working hours</dt><dd>{form.settings.opening_time} – {form.settings.closing_time}</dd></div><div><dt>Working days</dt><dd>{form.settings.working_days.length} days</dd></div><div><dt>Currency</dt><dd>{form.currency_code}</dd></div><div><dt>Status</dt><dd className="success">{data?.factory?.status||'active'}</dd></div></dl></aside></form></section>
}
