import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, RefreshCw } from 'lucide-react';

async function api(){const response=await fetch('/api/procurement/overview',{headers:{Accept:'application/json'}});const text=await response.text();let data:any;try{data=JSON.parse(text)}catch{throw new Error('Purchasing data could not be read. Please sign in again.')}if(!response.ok)throw new Error(data.message||'Purchasing data could not be loaded.');return data}
const money=(value:any,currency='RWF')=>new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:currency==='RWF'?0:2}).format(Number(value||0));
const typeForTab:Record<string,string>={requests:'purchase_request',orders:'purchase_order',receipts:'goods_receipt'};
const titles:Record<string,string>={requests:'Purchase requests',prices:'Supplier prices',orders:'Purchase orders',receipts:'Received goods'};

export default function ProcurementOverviewPage(){
    const [data,setData]=useState<any>(null);const [tab,setTab]=useState('requests');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [updated,setUpdated]=useState<Date|null>(null);
    const load=async(silent=false)=>{if(!silent)setLoading(true);try{setData(await api());setUpdated(new Date());setError('')}catch(reason:any){if(!silent)setError(reason.message)}finally{if(!silent)setLoading(false)}};
    useEffect(()=>{load();const timer=window.setInterval(()=>load(true),15000);return()=>window.clearInterval(timer)},[]);
    const summary=data?.summary||{};const rows=useMemo(()=>(data?.documents?.data||[]).filter((item:any)=>item.document_type===typeForTab[tab]),[data,tab]);
    return <section className="module-page procurement-live-page"><div className="module-hero"><div className="module-title"><div><div className="eyebrow"><i></i>LIVE PURCHASING DATA</div><h1>Purchasing overview</h1><p>Monitor purchase requests, supplier prices, purchase orders and received goods recorded by your purchasing team.</p><small className="sales-updated">{updated?'Last updated '+updated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Connecting to purchasing records…'}</small></div></div><button className="secondary-btn" disabled={loading} onClick={()=>load()}><RefreshCw className={loading?'spin':''} size={16}/>{loading?'Refreshing…':'Refresh data'}</button></div>
        {error&&<div className="admin-alert error"><AlertTriangle size={18}/>{error}</div>}
        <div className="sales-metrics"><Metric label="Pending requests" value={summary.pending_requests}/><Metric label="Open purchase orders" value={summary.open_orders}/><Metric label="Ordered value" value={money(summary.ordered_value)}/><Metric label="Active suppliers" value={summary.active_suppliers}/></div>
        <div className="module-tabs sales-tabs">{[['requests','Purchase requests',summary.requests],['prices','Supplier prices',summary.suppliers],['orders','Purchase orders',summary.purchase_orders],['receipts','Received goods',summary.receipts]].map(([key,label,count]:any)=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{Number(count||0).toLocaleString()}</span></button>)}</div>
        {tab==='prices'?<PriceTable suppliers={data?.supplier_prices||[]}/>:<DocumentTable rows={rows} tab={tab}/>}</section>;
}
function DocumentTable({rows,tab}:any){return <section className="panel sales-records"><header><div><h2>{titles[tab]}</h2><p>Records shown below come directly from this factory’s purchasing database.</p></div></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Number</th><th>Supplier</th><th>Date</th><th>Items</th><th>Total</th><th>Status</th><th>{tab==='receipts'?'Received at':'Expected date'}</th></tr></thead><tbody>{rows.length?rows.map((item:any)=><tr key={item.id}><td><b>{item.document_number}</b></td><td>{item.supplier?.name||'Not assigned'}<small>{item.supplier?.code||''}</small></td><td>{new Date(item.document_date+'T12:00:00').toLocaleDateString()}</td><td>{Number(item.line_count||0).toLocaleString()}</td><td>{money(item.total_amount,item.currency_code)}</td><td><span className={'admin-status '+item.status}>{String(item.status).replaceAll('_',' ')}</span></td><td>{tab==='receipts'?(item.received_at?new Date(item.received_at).toLocaleString():'Not recorded'):(item.expected_date?new Date(item.expected_date+'T12:00:00').toLocaleDateString():'Not set')}</td></tr>):<tr><td colSpan={7}><Empty text={'No '+titles[tab].toLowerCase()+' have been recorded yet.'}/></td></tr>}</tbody></table></div></section>}
function PriceTable({suppliers}:any){const rows=suppliers.flatMap((supplier:any)=>(supplier.items||[]).map((item:any)=>({supplier,item,...item.pivot})));return <section className="panel sales-records"><header><div><h2>Supplier prices</h2><p>Current item prices and lead times registered for factory suppliers.</p></div></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Supplier</th><th>Item</th><th>Supplier SKU</th><th>Unit price</th><th>Lead time</th><th>Minimum order</th></tr></thead><tbody>{rows.length?rows.map((row:any)=><tr key={row.supplier.id+'-'+row.item.id}><td><b>{row.supplier.name}</b></td><td>{row.item.name}<small>{row.item.sku}</small></td><td>{row.supplier_sku||'Not set'}</td><td>{money(row.unit_price)}</td><td>{Number(row.lead_time_days||0)} days</td><td>{Number(row.minimum_order_quantity||0).toLocaleString()}</td></tr>):<tr><td colSpan={6}><Empty text="No supplier prices have been registered yet."/></td></tr>}</tbody></table></div></section>}
function Metric({label,value}:any){return <article className="panel"><small>{label}</small><strong>{typeof value==='string'?value:Number(value||0).toLocaleString()}</strong></article>}
function Empty({text}:any){return <div className="sales-empty"><b>No records available</b><span>{text}</span></div>}
