import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {RefreshCw} from 'lucide-react';

const csrf=()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content||'';
async function request(url:string){const response=await fetch(url,{headers:{Accept:'application/json','X-CSRF-TOKEN':csrf()}});const text=await response.text();let payload:any={};try{payload=text?JSON.parse(text):{}}catch{throw new Error('The server returned an invalid response. Please sign in again.')}if(!response.ok)throw new Error(payload.message||'Unable to load product data.');return payload}

export default function ProductCatalogPage({user,locale}:{user:any;locale:'en'|'fr'}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('items'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState<Date|null>(null);
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{setData(await request('/api/products/overview'));setUpdated(new Date());setError('')}catch(reason:any){setError(reason.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const timer=window.setInterval(()=>load(true),15000);return()=>window.clearInterval(timer)},[load]);
 const money=(value:any)=>new Intl.NumberFormat(locale==='fr'?'fr-RW':'en-RW',{style:'currency',currency:user.current_factory?.currency_code||'RWF',maximumFractionDigits:0}).format(Number(value)||0);
 const quantity=(value:any,unit='')=>`${Number(value||0).toLocaleString(locale==='fr'?'fr-FR':'en-US',{maximumFractionDigits:3})}${unit?' '+unit:''}`;
 const units=useMemo(()=>new Map((data?.units||[]).map((unit:any)=>[unit.id,unit])),[data]);
 if(loading&&!data)return <section className="product-catalog-page"><div className="panel products-loading"><RefreshCw className="spin"/><h2>Loading products and materials</h2><p>Connecting to the factory database…</p></div></section>;
 return <section className="product-catalog-page"><header className="products-heading"><div><div className="eyebrow"><i></i>{locale==='fr'?'DONNÉES PRODUITS EN DIRECT':'LIVE PRODUCT DATA'}</div><h1>{locale==='fr'?'Produits et matériaux':'Products and materials'}</h1><p>{locale==='fr'?'Consultez les articles, catégories, recettes et unités enregistrés dans votre usine.':'View every item, category, product recipe and unit recorded for your factory.'}</p><small>{updated?(locale==='fr'?'Mis à jour ':'Updated ')+updated.toLocaleTimeString():''}</small></div><button className="secondary-btn" disabled={loading} onClick={()=>load()}><RefreshCw className={loading?'spin':''}/>{loading?'Refreshing…':'Refresh data'}</button></header>
 {error&&<div className="alert error">{error}</div>}
 {data&&<><div className="products-metrics"><Metric label="All items" value={data.summary.items}/><Metric label="Active items" value={data.summary.active_items}/><Metric label="Finished products" value={data.summary.finished_products}/><Metric label="Raw materials" value={data.summary.raw_materials}/><Metric label="Product recipes" value={data.summary.recipes}/></div>
 <nav className="panel products-tabs">{[['items','Products and item codes'],['categories','Categories'],['boms','Materials needed'],['units','Units and conversions']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{key==='items'?data.items.length:key==='categories'?data.categories.length:key==='boms'?data.boms.length:data.units.length}</span></button>)}</nav>
 <article className="panel products-data-panel">{tab==='items'?<Items rows={data.items} money={money} quantity={quantity}/>:tab==='categories'?<Categories rows={data.categories}/>:tab==='boms'?<Boms rows={data.boms} units={units} quantity={quantity}/>:<Units rows={data.units} conversions={data.conversions}/>}</article></>}
 </section>
}
function Metric({label,value}:any){return <article><span>{label}</span><strong>{Number(value||0).toLocaleString()}</strong></article>}
function PanelHeader({title,count}:any){return <header className="products-panel-header"><h2>{title}</h2><span>{count} {count===1?'record':'records'}</span></header>}
function Empty({columns,text}:any){return <tr><td colSpan={columns}><div className="products-empty"><b>{text}</b><span>New database records will appear here automatically.</span></div></td></tr>}
function Items({rows,money,quantity}:any){return <><PanelHeader title="Products and item codes" count={rows.length}/><div className="admin-table-wrap"><table className="admin-table products-table"><thead><tr><th>Item</th><th>Code</th><th>Type</th><th>Category</th><th>Unit</th><th>On hand</th><th>Unit cost</th><th>Stock value</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map((item:any)=><tr key={item.id}><td><b>{item.name}</b><small>{item.description||'No description'}</small></td><td>{item.sku}</td><td>{String(item.type).replaceAll('_',' ')}</td><td>{item.category_name||'Not categorized'}</td><td>{item.unit?.name||'—'} ({item.unit?.symbol||'—'})</td><td>{quantity(item.quantity_on_hand,item.unit?.symbol)}</td><td>{money(item.standard_cost)}</td><td>{money(item.stock_value)}</td><td><span className={`admin-status ${item.is_active?'active':'suspended'}`}>{item.is_active?'Active':'Inactive'}</span></td></tr>):<Empty columns={9} text="No products or materials have been recorded yet."/>}</tbody></table></div></>}
function Categories({rows}:any){return <><PanelHeader title="Item categories" count={rows.length}/><div className="admin-table-wrap"><table className="admin-table products-table compact"><thead><tr><th>Code</th><th>Category</th><th>Parent category</th><th>Items</th></tr></thead><tbody>{rows.length?rows.map((item:any)=><tr key={item.id}><td><b>{item.code}</b></td><td>{item.name}</td><td>{item.parent_id||'None'}</td><td>{item.items_count}</td></tr>):<Empty columns={4} text="No item categories have been created yet."/>}</tbody></table></div></>}
function Boms({rows,units,quantity}:any){return <><PanelHeader title="Product recipes and materials needed" count={rows.length}/><div className="products-recipes">{rows.length?rows.map((bom:any)=><section key={bom.id}><header><div><h3>{bom.item?.name||bom.name}</h3><p>{bom.name} · Version {bom.version}</p></div><span className={`admin-status ${bom.status==='active'?'active':'pending'}`}>{bom.status}</span></header><div className="recipe-summary"><span>Output <b>{quantity(bom.output_quantity,(units.get(bom.item?.unit_id) as any)?.symbol)}</b></span><span>Expected waste <b>{Number(bom.expected_waste_percent||0)}%</b></span><span>Components <b>{bom.components.length}</b></span></div><table className="admin-table products-table"><thead><tr><th>Material</th><th>Code</th><th>Quantity needed</th><th>Waste</th><th>Required</th></tr></thead><tbody>{bom.components.map((component:any)=>{const unit:any=units.get(component.unit_id);return <tr key={component.id}><td><b>{component.item?.name||'Unknown item'}</b></td><td>{component.item?.sku||'—'}</td><td>{quantity(component.quantity,unit?.symbol)}</td><td>{Number(component.waste_percent||0)}%</td><td>{component.is_optional?'Optional':'Required'}</td></tr>})}</tbody></table></section>):<div className="products-empty"><b>No product recipes have been recorded yet.</b><span>Recipes created by the production manager will appear here.</span></div>}</div></>}
function Units({rows,conversions}:any){return <><PanelHeader title="Units and conversions" count={rows.length}/><div className="products-units-grid"><section><h3>Measurement units</h3><table className="admin-table products-table compact"><thead><tr><th>Unit</th><th>Symbol</th><th>Measurement</th><th>Precision</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map((unit:any)=><tr key={unit.id}><td><b>{unit.name}</b></td><td>{unit.symbol}</td><td>{unit.dimension}</td><td>{unit.precision}</td><td>{unit.is_active?'Active':'Inactive'}</td></tr>):<Empty columns={5} text="No units are available."/>}</tbody></table></section><section><h3>Unit conversions</h3><table className="admin-table products-table compact"><thead><tr><th>From</th><th>Conversion</th><th>To</th></tr></thead><tbody>{conversions.length?conversions.map((item:any)=><tr key={item.id}><td>1 {item.from_symbol}</td><td>× {Number(item.multiplier).toLocaleString(undefined,{maximumFractionDigits:8})}</td><td>{item.to_symbol}</td></tr>):<Empty columns={3} text="No unit conversions have been configured."/>}</tbody></table></section></div></>}
