import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, Factory, PackageCheck, Play, Plus, RefreshCw, Save } from 'lucide-react';

async function api(url:string,options:RequestInit={}) {
    const response=await fetch(url,{...options,headers:{Accept:'application/json','Content-Type':'application/json',...(options.headers||{})}});
    const text=await response.text();let data:any;
    try{data=JSON.parse(text)}catch{throw new Error('The server returned an unreadable response. Please try again.')}
    if(!response.ok){const details=Object.values(data.errors||{}).flat().join(' ');throw new Error(details||data.message||'The action could not be completed.')}
    return data;
}
const blank=()=>({order_number:'PO-'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+String(Date.now()).slice(-4),bill_of_material_id:'',workflow_template_id:'',planned_quantity:'',planned_start:new Date().toISOString().slice(0,10),planned_end:''});
const statusLabel:Record<string,string>={draft:'Needs approval',approved:'Ready to produce',in_progress:'In production',paused:'Paused',completed:'Completed',cancelled:'Cancelled',not_started:'Waiting for previous step',ready:'Ready to start',blocked:'Blocked',failed:'Failed',rework:'Needs rework'};

export default function ProductionOperations({can}:any){
    const [data,setData]=useState<any>(null);const [form,setForm]=useState<any>(blank());const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [stageEdits,setStageEdits]=useState<Record<number,any>>({});
    const load=async()=>{setLoading(true);try{setData(await api('/api/manufacturing/overview'));setError('')}catch(reason:any){setError(reason.message)}finally{setLoading(false)}};useEffect(()=>{load();const timer=window.setInterval(()=>load(),5000);return()=>window.clearInterval(timer)},[]);
    const orders=data?.orders?.data||[];const recipes=data?.boms||[];const processes=(data?.workflows||[]).filter((item:any)=>item.status==='active');const stages=orders.flatMap((order:any)=>(order.executions||[]).map((stage:any)=>({...stage,order_number:order.order_number,product:order.item?.name||'Product'})));
    const metrics=useMemo(()=>({approval:orders.filter((item:any)=>item.status==='draft').length,active:orders.filter((item:any)=>['approved','in_progress','paused'].includes(item.status)).length,completed:orders.filter((item:any)=>item.status==='completed').length,late:orders.filter((item:any)=>item.planned_end&&new Date(item.planned_end+'T23:59:59')<new Date()&&!['completed','cancelled'].includes(item.status)).length}),[orders]);
    const create=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');setSuccess('');try{const recipe=recipes.find((item:any)=>String(item.id)===String(form.bill_of_material_id));if(!recipe)throw new Error('Choose a product recipe.');await api('/api/manufacturing/orders',{method:'POST',body:JSON.stringify({...form,item_id:recipe.item_id,planned_quantity:Number(form.planned_quantity),planned_end:form.planned_end||null})});setForm(blank());setOpen(false);setSuccess('Production order created. Review it below, then approve it when materials are ready.');await load()}catch(reason:any){setError(reason.message)}finally{setBusy(false)}};
    const approve=async(id:number)=>{setBusy(true);setError('');setSuccess('');try{await api('/api/manufacturing/orders/'+id+'/approve',{method:'POST'});setSuccess('Order approved. The first production step is now ready to start.');await load()}catch(reason:any){setError(reason.message)}finally{setBusy(false)}};
    const editStage=(id:number,field:string,value:any)=>setStageEdits(current=>({...current,[id]:{...(current[id]||{}),[field]:value}}));
    const saveStage=async(stage:any,nextStatus:string)=>{const values=stageEdits[stage.id]||{};setBusy(true);setError('');setSuccess('');try{await api('/api/manufacturing/stages/'+stage.id,{method:'PATCH',body:JSON.stringify({status:nextStatus,output_quantity:Number(values.output_quantity??stage.output_quantity??0),rejected_quantity:Number(values.rejected_quantity??stage.rejected_quantity??0),waste_quantity:Number(values.waste_quantity??stage.waste_quantity??0),downtime_minutes:Number(values.downtime_minutes??stage.downtime_minutes??0)})});setSuccess(nextStatus==='completed'?'Production step completed. The next step is now ready.':'Production step updated.');await load()}catch(reason:any){setError(reason.message)}finally{setBusy(false)}};
    return <section className="module-page production-operations">
        <div className="module-hero"><div className="module-title"><span><Factory size={22}/></span><div><div className="eyebrow"><i></i>LIVE PRODUCTION</div><h1>Production orders</h1><p>Create production work, check progress and record results for each step.</p></div></div><div className="workflow-actions"><button className="secondary-btn" disabled={loading} onClick={load}><RefreshCw className={loading?'spin':''} size={16}/>{loading?'Refreshing…':'Refresh'}</button>{can('production.plan')&&<button className="primary-btn" disabled={!recipes.length||!processes.length} onClick={()=>setOpen(!open)}><Plus size={16}/>{open?'Close form':'Create production order'}</button>}</div></div>
        {error&&<div className="admin-alert error"><AlertTriangle size={18}/><span>{error}</span></div>}{success&&<div className="admin-alert success"><CheckCircle2 size={18}/><span>{success}</span></div>}
        {(!recipes.length||!processes.length)&&!loading&&<div className="production-setup-warning"><AlertTriangle/><div><b>Production setup is not complete</b><p>{!recipes.length?'A product recipe must be created before a production order can be added. ':''}{!processes.length?'The Factory Manager must activate a production process before work can begin.':''}</p></div></div>}
        <section className="production-summary"><Summary icon={<Clock3/>} label="Needs approval" value={metrics.approval}/><Summary icon={<Play/>} label="Active orders" value={metrics.active}/><Summary icon={<PackageCheck/>} label="Completed orders" value={metrics.completed}/><Summary icon={<AlertTriangle/>} label="Past due" value={metrics.late} danger={metrics.late>0}/></section>
        {open&&<form className="panel admin-form production-order-form" onSubmit={create}><header><div><h2>Create a production order</h2><p>Choose what to produce, how many units are needed and when the work should finish.</p></div></header><div className="form-grid"><label>Order number<input required value={form.order_number} onChange={event=>setForm({...form,order_number:event.target.value})}/><small>Created automatically. You can change it if needed.</small></label><label>Product recipe<select required value={form.bill_of_material_id} onChange={event=>setForm({...form,bill_of_material_id:event.target.value})}><option value="">Choose what to produce</option>{recipes.map((item:any)=><option key={item.id} value={item.id}>{item.item?.name||item.name} — Recipe {item.version}</option>)}</select><small>The recipe lists the materials required for the product.</small></label><label>Production process<select required value={form.workflow_template_id} onChange={event=>setForm({...form,workflow_template_id:event.target.value})}><option value="">Choose the production steps</option>{processes.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><small>The process controls the order of production steps.</small></label><label>Quantity to produce<input required type="number" min="0.01" step="0.01" value={form.planned_quantity} onChange={event=>setForm({...form,planned_quantity:event.target.value})}/></label><label>Start date<input type="date" value={form.planned_start} onChange={event=>setForm({...form,planned_start:event.target.value})}/></label><label>Finish by<input type="date" min={form.planned_start} value={form.planned_end} onChange={event=>setForm({...form,planned_end:event.target.value})}/></label></div><button className="primary-btn" disabled={busy}><Save size={16}/>{busy?'Creating order…':'Create order'}</button></form>}
        <section className="panel production-section"><header className="production-section-head"><div><h2>Production orders</h2><p>Approve new orders and check how much work is complete.</p></div></header><div className="admin-table-wrap borderless"><table className="admin-table"><thead><tr><th>Order</th><th>Product</th><th>Progress</th><th>Status</th><th>Steps</th><th>Finish by</th><th>Next action</th></tr></thead><tbody>{orders.length?orders.map((item:any)=>{const progress=Number(item.planned_quantity)>0?Math.min(100,Math.round(Number(item.completed_quantity||0)/Number(item.planned_quantity)*100)):0;return <tr key={item.id}><td><b>{item.order_number}</b></td><td>{item.item?.name||'Product'}</td><td><div className="simple-progress"><span style={{width:progress+'%'}}></span></div><small>{Number(item.completed_quantity||0).toLocaleString()} of {Number(item.planned_quantity||0).toLocaleString()} units</small></td><td><span className={'admin-status '+item.status}>{statusLabel[item.status]||item.status}</span></td><td>{item.executions?.filter((step:any)=>step.status==='completed').length||0} of {item.executions?.length||0} complete</td><td>{item.planned_end?new Date(item.planned_end+'T12:00:00').toLocaleDateString():'No date set'}</td><td>{item.status==='draft'&&can('production.approve')?<button className="table-action" disabled={busy} onClick={()=>approve(item.id)}><CheckCircle2 size={15}/>Check materials and approve</button>:<span className="muted-action">{item.status==='completed'?'Finished':'No action needed'}</span>}</td></tr>}):<tr><td colSpan={7}><Empty title="No production orders yet" text="Use “Create production order” to add the first order."/></td></tr>}</tbody></table></div></section>
        <section className="panel production-section"><header className="production-section-head"><div><h2>Production steps</h2><p>Start ready work, record quantities and complete steps in the correct order.</p></div></header>{stages.length?<div className="production-step-list">{stages.map((stage:any)=>{const edit=stageEdits[stage.id]||{};const canRecord=['ready','in_progress','blocked','rework'].includes(stage.status);return <article className="production-step" key={stage.id}><div className="production-step-title"><span className={'step-dot '+stage.status}></span><div><b>{stage.stage?.name||'Production step'}</b><small>{stage.order_number} · {stage.product}</small></div><em className={'admin-status '+stage.status}>{statusLabel[stage.status]||stage.status.replaceAll('_',' ')}</em></div>{canRecord&&<div className="production-result-fields"><label>Units produced<input type="number" min="0" value={edit.output_quantity??stage.output_quantity??0} onChange={event=>editStage(stage.id,'output_quantity',event.target.value)}/></label><label>Units rejected<input type="number" min="0" value={edit.rejected_quantity??stage.rejected_quantity??0} onChange={event=>editStage(stage.id,'rejected_quantity',event.target.value)}/></label><label>Waste<input type="number" min="0" value={edit.waste_quantity??stage.waste_quantity??0} onChange={event=>editStage(stage.id,'waste_quantity',event.target.value)}/></label><label>Stopped time (minutes)<input type="number" min="0" value={edit.downtime_minutes??stage.downtime_minutes??0} onChange={event=>editStage(stage.id,'downtime_minutes',event.target.value)}/></label></div>}<div className="production-step-actions">{stage.status==='ready'&&<button className="primary-btn" disabled={busy} onClick={()=>saveStage(stage,'in_progress')}><Play size={15}/>Start this step</button>}{stage.status==='in_progress'&&<><button className="secondary-btn" disabled={busy} onClick={()=>saveStage(stage,'blocked')}>Mark as blocked</button><button className="primary-btn" disabled={busy} onClick={()=>saveStage(stage,'completed')}><CheckCircle2 size={15}/>Complete step</button></>}{stage.status==='blocked'&&<button className="primary-btn" disabled={busy} onClick={()=>saveStage(stage,'in_progress')}><Play size={15}/>Resume work</button>}{stage.status==='rework'&&<button className="primary-btn" disabled={busy} onClick={()=>saveStage(stage,'in_progress')}><Play size={15}/>Start rework</button>}{stage.status==='not_started'&&<span>Complete the previous step first.</span>}{stage.status==='completed'&&<span className="completed-label"><CheckCircle2 size={16}/>Step completed</span>}</div></article>})}</div>:<Empty title="No production steps are active" text="Approve a production order to create its production steps."/>}</section>
    </section>
}
function Summary({icon,label,value,danger=false}:any){return <article className={'panel production-summary-card '+(danger?'danger':'')}><span>{icon}</span><div><small>{label}</small><b>{Number(value||0).toLocaleString()}</b></div></article>}
function Empty({title,text}:any){return <div className="production-empty"><PackageCheck size={28}/><b>{title}</b><span>{text}</span></div>}
