import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, RefreshCw } from 'lucide-react';

async function api(url:string){const response=await fetch(url,{headers:{Accept:'application/json'}});const text=await response.text();let data:any;try{data=JSON.parse(text)}catch{throw new Error('Sales data could not be read. Please sign in again.')}if(!response.ok)throw new Error(data.message||'Sales data could not be loaded.');return data}
const labels:Record<string,string>={customer_order:'Customer order',quotation:'Quotation',invoice:'Invoice',return:'Return'};
const money=(value:any,currency='RWF')=>new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:currency==='RWF'?0:2}).format(Number(value||0));

export default function SalesOverviewPage(){
    const [data,setData]=useState<any>(null);const [tab,setTab]=useState('customer_order');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [updated,setUpdated]=useState<Date|null>(null);
    const load=async(silent=false)=>{if(!silent)setLoading(true);try{setData(await api('/api/sales/overview'));setUpdated(new Date());setError('')}catch(reason:any){if(!silent)setError(reason.message)}finally{if(!silent)setLoading(false)}};
    useEffect(()=>{load();const timer=window.setInterval(()=>load(true),15000);return()=>window.clearInterval(timer)},[]);
    const summary=data?.summary||{};const rows=useMemo(()=>(data?.documents?.data||[]).filter((item:any)=>item.document_type===tab),[data,tab]);
    const title=labels[tab]+'s';
    return <section className="module-page sales-live-page">
        <div className="module-hero"><div className="module-title"><div><div className="eyebrow"><i></i>LIVE SALES DATA</div><h1>Sales overview</h1><p>Monitor customer orders, quotations, invoices, payments and returns recorded by your sales team.</p><small className="sales-updated">{updated?'Last updated '+updated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Connecting to sales records…'}</small></div></div><button className="secondary-btn" disabled={loading} onClick={()=>load()}><RefreshCw className={loading?'spin':''} size={16}/>{loading?'Refreshing…':'Refresh data'}</button></div>
        {error&&<div className="admin-alert error"><AlertTriangle size={18}/>{error}</div>}
        <div className="sales-metrics"><Metric label="Customer orders" value={summary.customer_orders}/><Metric label="Active orders" value={summary.active_orders}/><Metric label="Invoice value" value={money(summary.invoiced_amount)}/><Metric label="Outstanding payments" value={money(summary.outstanding_amount)} warning={summary.outstanding_amount>0}/></div>
        <div className="module-tabs sales-tabs">{[['customer_order','Customer orders',summary.customer_orders],['quotation','Quotations',summary.quotations],['invoice','Invoices',summary.invoices],['return','Returns',summary.returns]].map(([key,label,count]:any)=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{Number(count||0).toLocaleString()}</span></button>)}</div>
        <section className="panel sales-records"><header><div><h2>{title}</h2><p>Records shown below come directly from this factory’s sales database.</p></div></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Number</th><th>Customer</th><th>Date</th><th>Items</th><th>Total</th>{tab==='invoice'&&<th>Paid</th>}<th>Status</th><th>Due date</th></tr></thead><tbody>{rows.length?rows.map((item:any)=><tr key={item.id}><td><b>{item.document_number}</b></td><td><b>{item.customer_name}</b>{item.customer_email&&<small>{item.customer_email}</small>}</td><td>{new Date(item.document_date+'T12:00:00').toLocaleDateString()}</td><td>{Number(item.item_count||0).toLocaleString()}</td><td>{money(item.total_amount,item.currency_code)}</td>{tab==='invoice'&&<td>{money(item.paid_amount,item.currency_code)}</td>}<td><span className={'admin-status '+item.status}>{String(item.status).replaceAll('_',' ')}</span></td><td>{item.due_date?new Date(item.due_date+'T12:00:00').toLocaleDateString():'Not set'}</td></tr>):<tr><td colSpan={tab==='invoice'?8:7}><div className="sales-empty"><b>No {title.toLowerCase()} recorded</b><span>Records will appear here automatically when the sales team adds them.</span></div></td></tr>}</tbody></table></div></section>
    </section>;
}
function Metric({label,value,warning=false}:any){return <article className={'panel '+(warning?'warning':'')}><small>{label}</small><strong>{value??0}</strong></article>}
